export const REQUEST_REGIONS = 'REQUEST_REGIONS';
export type REQUEST_REGIONS = typeof REQUEST_REGIONS;

export const RECEIVE_REGIONS = 'RECEIVE_REGIONS';
export type RECEIVE_REGIONS = typeof RECEIVE_REGIONS;

export const REQUEST_PING = 'REQUEST_PING';
export type REQUEST_PING = typeof REQUEST_PING;

export const RECEIVE_PING = 'RECEIVE_PING';
export type RECEIVE_PING = typeof RECEIVE_PING;

export const REQUEST_REALMS = 'REQUEST_REALMS';
export type REQUEST_REALMS = typeof REQUEST_REALMS;

export const RECEIVE_REALMS = 'RECEIVE_REALMS';
export type RECEIVE_REALMS = typeof RECEIVE_REALMS;

export const REGION_CHANGE = 'REGION_CHANGE';
export type REGION_CHANGE = typeof REGION_CHANGE;

export const REALM_CHANGE = 'REALM_CHANGE';
export type REALM_CHANGE = typeof REALM_CHANGE;
